[project]
name = "systemmonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.2.1",
    "pyside6>=6.10.1",
]
